// Shared domain types for GridPath. These mirror §8 of the PRD.

export type GridPointType = "line" | "minor_line" | "pole" | "transformer" | "substation";

export type ServiceMode = "overhead" | "underground";

/**
 * How the property reaches the grid.
 * - "house": connect directly at the existing pole/meter — no wire run needed.
 * - "standard": run a new service line to the property (distance-based cost).
 */
export type WireScenario = "house" | "standard";

export type PropertyType = "new_build" | "land" | "adu" | "load_upgrade";

export interface LatLon {
  lat: number;
  lon: number;
}

/** A single power feature returned from Overpass, normalized for the map. */
export interface PowerFeature {
  id: string;
  type: GridPointType;
  /** Node features have a single point; way features have an ordered path. */
  geometry: LatLon[];
}

export interface CostBreakdown {
  baseConnectionFee: number;
  lineExtension: number;
  transformer: number;
  meterServiceDrop: number;
}

export interface EstimatedCost {
  total: number;
  breakdown: CostBreakdown;
}

export interface EstimatedTimeline {
  min: number;
  max: number;
  unit: "weeks" | "months";
  /** Plain-language label, e.g. "6–12 weeks". */
  label: string;
  /** Flat application/review note shown as subtext, e.g. "+2 weeks application & review". */
  applicationNote: string;
}

export interface ConnectionEstimate {
  id: string;
  address: string;
  coordinates: LatLon;
  nearestGridPoint: LatLon & { type: GridPointType };
  distanceFeet: number;
  needsTransformer: boolean;
  mode: ServiceMode;
  /** Whether a new line run is needed ("standard") or the property connects at the pole ("house"). */
  wireScenario: WireScenario;
  estimatedCost: EstimatedCost;
  estimatedTimeline: EstimatedTimeline;
  /** One-line, human-readable explanation of how the numbers were derived. */
  explanation: string;
  /** Nearby power features for the optional map overlay. */
  features: PowerFeature[];
  /** True when results came from the bundled fallback fixture, not live Overpass. */
  fromFixture: boolean;
}

export interface ApplicationLead {
  estimateId: string;
  name: string;
  email: string;
  phone: string;
  propertyType: PropertyType;
  submittedAt: string;
}

export interface GeocodeResult {
  label: string;
  lat: number;
  lon: number;
}

// ---- Grants & offer ----

/** A single grant/rebate that can be applied against the connection cost. */
export interface Grant {
  id: string;
  name: string;
  /** Issuing body, e.g. "USDA Rural Energy for America". */
  authority: string;
  /** One-line plain-language description. */
  detail: string;
  /** Face value in USD. */
  amount: number;
}

/** The connection "offer" with grants applied to reach a much cheaper net cost. */
export interface GrantOffer {
  /** The full connection cost before assistance — the "offer". */
  gross: number;
  grants: Grant[];
  /** Total assistance actually applied (capped so you always pay something). */
  totalApplied: number;
  /** Net cost after grants. */
  net: number;
  /** Percent saved vs the gross offer. */
  percentOff: number;
}

// ---- Clean-energy advisor ----

/** Grounding data about a property's clean-energy potential (real or dummy). */
export interface PropertySignals {
  address: string;
  region: string;
  /** Usable rooftop area for solar, sq ft. */
  roofAreaSqFt: number;
  /** Max number of standard panels that fit. */
  maxPanels: number;
  /** Peak sun hours per year. */
  sunHoursPerYear: number;
  /** Estimated annual solar production potential, kWh. */
  solarPotentialKwh: number;
  /** Local utility electricity rate, $/kWh. */
  utilityRate: number;
  /** Estimated current annual household electricity use, kWh. */
  annualUsageKwh: number;
  /** Estimated current annual electricity bill, USD. */
  annualBill: number;
  /** Grid carbon intensity, kg CO2 per kWh. */
  gridCarbonKgPerKwh: number;
  /** True when rooftop figures came from the Google Solar API, not estimates. */
  fromSolarApi: boolean;
}

export interface CleanEnergyOption {
  key: string;
  name: string;
  icon: string;
  recommended: boolean;
  headline: string;
  whatItIs: string;
  estimatedCost: number;
  annualSavings: number;
  paybackYears: number;
  co2ReductionTons: number;
  incentives: string[];
  priority: number;
}

export interface CleanEnergyPlan {
  headline: string;
  summary: string;
  cleanScoreBefore: number;
  cleanScoreAfter: number;
  options: CleanEnergyOption[];
  recommendedBundle: {
    items: string[];
    totalCost: number;
    totalAnnualSavings: number;
    note: string;
  };
  /** "claude" when generated by the model, "fallback" when computed locally. */
  source: "claude" | "fallback";
  signals: PropertySignals;
  /**
   * Multi-year "is going solar worth it?" risk/ROI analysis for the recommended
   * solar option. Computed deterministically server-side (never by the LLM) and
   * attached after the plan is built. Optional so existing consumers are unaffected.
   */
  roi?: RoiAnalysis;
}

// ---- ROI / "is it worth it?" risk analysis ----
//
// An honest, multi-year cash-flow model layered on top of a CleanEnergyOption.
// Everything here is an ESTIMATE under stated assumptions — never a guarantee.
// The numbers are computed by a deterministic engine (src/lib/roi.ts); any
// Claude narration only *explains* these numbers, it never produces them.

/** Tunable, disclosed assumptions behind the ROI model. All defaults are conservative. */
export interface RoiAssumptions {
  /** Annual utility electricity price escalation, % (e.g. 3 = 3%/yr). */
  electricityEscalationPct: number;
  /** Annual solar panel output degradation, % (solar only). */
  panelDegradationPct: number;
  /** Discount rate for NPV / discounted payback, % (time value of money). */
  discountRatePct: number;
  /** Analysis horizon in years. */
  analysisYears: number;
  /** Ongoing operations & maintenance cost, $/yr. */
  annualOmCost: number;
  /** Year a one-time inverter replacement is modeled (solar only); 0 to disable. */
  inverterReplacementYear: number;
  /** Cost of that inverter replacement, USD. */
  inverterReplacementCost: number;
}

/** One year of the modeled cash flow. */
export interface RoiYear {
  year: number;
  /** Gross energy savings this year (after escalation + degradation), USD. */
  grossSavings: number;
  /** Net cash flow this year (savings − O&M − any one-time costs), USD. */
  netCashflow: number;
  /** Cumulative net position vs the upfront cost (undiscounted), USD. */
  cumulative: number;
  /** Cumulative net position discounted to present value, USD. */
  cumulativeDiscounted: number;
}

/** One scenario in the electricity-price sensitivity sweep. */
export interface SensitivityScenario {
  label: "Low" | "Base" | "High";
  escalationPct: number;
  /** null when the system never pays back within the horizon. */
  simplePaybackYears: number | null;
  lifetimeNetSavings: number;
  /** Estimated equivalent annual return, %; null when undefined. */
  irrPct: number | null;
}

export interface RoiAnalysis {
  optionKey: string;
  optionName: string;
  /** Net upfront cost after incentives, USD. */
  netCost: number;
  analysisYears: number;
  assumptions: RoiAssumptions;
  /** Year the cumulative (undiscounted) savings first cover the cost; null if never. */
  simplePaybackYears: number | null;
  /** Same, but in present-value terms (usually longer); null if never. */
  discountedPaybackYears: number | null;
  /** Whole-horizon net savings after upfront cost, O&M, degradation, escalation. */
  lifetimeNetSavings: number;
  /** Net present value of the full cash flow at the discount rate, USD. */
  npv: number;
  /** Internal rate of return as a %, framed as an estimate; null when undefined. */
  irrPct: number | null;
  /** First-year energy savings, USD. */
  firstYearSavings: number;
  /** First-year savings as a % of net cost (quick sanity ratio). */
  firstYearReturnPct: number;
  /** Integer year the investment breaks even; null if never within the horizon. */
  breakEvenYear: number | null;
  /** Per-year cash-flow series driving the payback curve. */
  years: RoiYear[];
  /** Low / base / high electricity-price sensitivity. */
  sensitivity: SensitivityScenario[];
  /** Provenance-driven confidence in the inputs. */
  confidence: "High" | "Medium" | "Low";
  /** Optional plain-language framing from Claude; null when no key/declined. */
  narrative: string | null;
}
